# Google Cloud Build configuration for automated deployment
steps:
  # Step 1: Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Build the frontend
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'
      - 'VITE_API_BASE_URL=https://${_SERVICE_NAME}-dot-${PROJECT_ID}.uc.r.appspot.com/api'

  # Step 3: Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

# Substitutions for dynamic values
substitutions:
  _SERVICE_NAME: 'akc-revisions' # Change this to your preferred service name

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1200s'
