Write-Host "`n🚀 SETTING UP LOCAL DEVELOPMENT ENVIRONMENT" -ForegroundColor Green
Write-Host "======================================" -ForegroundColor Green

# Check if .env already exists
if (Test-Path ".env") {
    Write-Host "`n⚠️  .env file already exists!" -ForegroundColor Yellow
    $response = Read-Host "Do you want to overwrite it? (y/n)"
    if ($response -ne 'y') {
        Write-Host "Exiting without changes." -ForegroundColor Red
        exit
    }
}

# Create .env file for local development
$envContent = @"
# Local Development Environment Variables
# Generated by setup-local-dev.ps1

# Supabase Configuration (same for both local and production)
VITE_SUPABASE_URL=https://zrxezqllmpdlhiudutme.supabase.co
VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyeGV6cWxsbXBkbGhpdWR1dG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0ODcyMzIsImV4cCI6MjA1NzA2MzIzMn0.zbmttNoNRALsW1aRV4VjodpitI_3opfNGhDgydcGhmQ

# Local Development URLs
VITE_API_BASE_URL=http://localhost:5173
VITE_APP_URL=http://localhost:5173

# Google OAuth
VITE_GOOGLE_CLIENT_ID=1061142868787-n4u3sjcg99s5b4hr112ncd62ql2b3e4c.apps.googleusercontent.com

# Google Maps API Key
VITE_GOOGLE_MAPS_API_KEY=AIzaSyCYCkSgaTqL25zJhMbwBnD4gMVlJzdSw0I

# Environment Flag
VITE_ENV=development
NODE_ENV=development

# Server Configuration for backend
PORT=3000
SERVER_PORT=3000
"@

# Write the .env file
$envContent | Out-File -FilePath ".env" -Encoding UTF8
Write-Host "✅ Created .env file for local development" -ForegroundColor Green

# Create or update server/.env
if (!(Test-Path "server")) {
    New-Item -ItemType Directory -Name "server" | Out-Null
}

$serverEnvContent = @"
# Server Environment Variables
PORT=3000
NODE_ENV=development

# Google Maps API Key (for server-side calls)
GOOGLE_MAPS_API_KEY=AIzaSyCYCkSgaTqL25zJhMbwBnD4gMVlJzdSw0I

# Supabase (if needed server-side)
SUPABASE_URL=https://zrxezqllmpdlhiudutme.supabase.co
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyeGV6cWxsbXBkbGhpdWR1dG1lIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTQ4NzIzMiwiZXhwIjoyMDU3MDYzMjMyfQ.4kv7pOUS551zS8DoA12lFw_4BVA0ByuQC76bRRMAkWY
"@

$serverEnvContent | Out-File -FilePath "server\.env" -Encoding UTF8
Write-Host "✅ Created server/.env file" -ForegroundColor Green

Write-Host "`n📋 NEXT STEPS:" -ForegroundColor Yellow
Write-Host "1. Update Supabase URL configuration:" -ForegroundColor White
Write-Host "   - Go to: https://supabase.com/dashboard/project/zrxezqllmpdlhiudutme/auth/url-configuration" -ForegroundColor Gray
Write-Host "   - Add http://localhost:5173 to allowed URLs" -ForegroundColor Gray

Write-Host "`n2. Update Google OAuth:" -ForegroundColor White
Write-Host "   - Go to: https://console.cloud.google.com/apis/credentials?project=crm-live-458710" -ForegroundColor Gray
Write-Host "   - Add http://localhost:5173 to authorized origins" -ForegroundColor Gray

Write-Host "`n3. Run the development servers:" -ForegroundColor White
Write-Host "   npm run dev:all" -ForegroundColor Cyan

Write-Host "`n✅ Setup complete! You can now develop locally." -ForegroundColor Green
