
export type StatusType = 
  | 'draft' 
  | 'sent' 
  | 'approved' 
  | 'rejected'
  | 'pending'
  | 'active'
  | 'inactive'
  | 'qualified'
  | 'potential'
  | 'prospect'
  | 'completed'
  | 'cancelled'
  | 'unknown'
  | 'on-hold'
  | 'NEW'
  | 'IN_PROGRESS'
  | 'SCHEDULED'
  | 'COMPLETED'
  | 'CANCELLED'
  | 'VERIFIED'
  | 'PAID'
  | 'UNPAID'
  | 'PARTIAL'
  | 'AWAITING_APPROVAL';
