
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrxezqllmpdlhiudutme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyeGV6cWxsbXBkbGhpdWR1dG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0ODcyMzIsImV4cCI6MjA1NzA2MzIzMn0.zbmttNoNRALsW1aRV4VjodpitI_3opfNGhDgydcGhmQ";

// Create client with explicit headers to ensure API key is always sent
// But avoid setting Content-Type globally to prevent upload issues
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        'apikey': SUPABASE_PUBLISHABLE_KEY,
        'Authorization': `Bearer ${SUPABASE_PUBLISHABLE_KEY}`
      },
    },
    db: {
      schema: 'public',
    },
    // Initialize storage settings with correct defaults
    storage: {
      // Don't limit the file sizes by default
      maxFileSize: 50 * 1024 * 1024, // 50MB max file size
    },
  }
);

// Helper to find the existing storage bucket with a consistent approach
export const findStorageBucket = async (targetName: string = 'construction_documents') => {
  try {
    // Get all available buckets
    const { data: buckets, error } = await supabase.storage.listBuckets();
    
    if (error) {
      console.error('Error listing buckets:', error);
      return null;
    }
    
    // Log all available buckets for debugging
    console.log('Available storage buckets:', buckets?.map(b => b.name));
    
    // First try exact case-sensitive match
    let bucket = buckets?.find(b => b.name === targetName);
    
    // If not found, try case-insensitive match
    if (!bucket) {
      bucket = buckets?.find(b => 
        b.name.toLowerCase() === targetName.toLowerCase()
      );
    }
    
    // If still not found, try more flexible match
    if (!bucket) {
      bucket = buckets?.find(b => 
        b.name.toLowerCase().includes('construction') && 
        b.name.toLowerCase().includes('document')
      );
    }
    
    if (bucket) {
      console.log(`Found storage bucket: ${bucket.name}`);
      return bucket;
    }
    
    console.warn(`No suitable storage bucket found matching "${targetName}"`);
    return null;
  } catch (err) {
    console.error('Error in findStorageBucket:', err);
    return null;
  }
};

// We won't try to create a bucket anymore since it's failing with RLS policy error
// Instead, we'll check for existing buckets and provide clear messaging to the user
export const ensureStorageBucket = async () => {
  try {
    const bucket = await findStorageBucket();
    
    if (bucket) {
      console.log(`Using existing bucket: ${bucket.name}`);
      return {
        success: true,
        bucketName: bucket.name
      };
    }
    
    // Since we can't create the bucket due to RLS policy, provide guidance
    console.warn('No construction documents bucket found and cannot create one due to permissions.');
    console.warn('Please create a "construction_documents" bucket in the Supabase dashboard.');
    
    return {
      success: false,
      error: 'Storage bucket not found and bucket creation failed due to permissions'
    };
  } catch (error) {
    console.error('Error in ensureStorageBucket:', error);
    return {
      success: false,
      error
    };
  }
};

// Check bucket status on initial load
ensureStorageBucket().then(result => {
  if (result.success) {
    console.log('Storage system initialized successfully');
  } else {
    console.warn('Storage system initialization failed:', result.error);
    console.warn('Document uploads may not work correctly');
  }
}).catch(console.error);
