// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://zrxezqllmpdlhiudutme.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyeGV6cWxsbXBkbGhpdWR1dG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0ODcyMzIsImV4cCI6MjA1NzA2MzIzMn0.zbmttNoNRALsW1aRV4VjodpitI_3opfNGhDgydcGhmQ';

// Create client with explicit headers to ensure API key is always sent
// But avoid setting Content-Type globally to prevent upload issues
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      apikey: SUPABASE_PUBLISHABLE_KEY,
    },
  },
});

supabase.auth.onAuthStateChange((event, session) => {
  console.log('[Supabase Auth]', event, session);
  if (event === 'INITIAL_SESSION') {
    // Handle initial session if needed
    console.log('[Supabase Auth] Initial session:', session);
  } else if (event === 'SIGNED_IN') {
    console.log('[Supabase Auth] User signed in:', session?.user?.email);
  } else if (event === 'SIGNED_OUT') {
    console.log('[Supabase Auth] User signed out');
  } else if (event === 'TOKEN_REFRESHED') {
    console.log('[Supabase Auth] Token refreshed:', session?.user?.email);
  } else if (event === 'USER_UPDATED') {
    console.log('[Supabase Auth] User updated:', session?.user?.email);
  } else if (event === 'PASSWORD_RECOVERY') {
    console.log('[Supabase Auth] Password recovery event');
  }
});
